Fix receive_error call scope to GremlinClient::Connection instead of WebSocket::Client::Simple::Client
Fixes "undefined method `receive_error' for #<WebSocket::Client::Simple::Client:0x00007f2779500d78> (NoMethodError)"